spring:
  application:
    name: server
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    enabled: false
#    baseline-on-migrate: true
#    baseline-version: 0
#    locations: classpath:db/migration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  token:
    validity: 18000
    prefix: Bearer
  signing:
    key: ${JWT_SIGNING_KEY}
  authorities:
    key: roles
  header:
    string: Authorization

server:
  port: ${PORT:8080}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

#logging:
#  level:
#    com.lawconnect: DEBUG
